### ISSUE TITLE
Prices do not match the data from the exchange

### ISSUE THREAD

**Issue by l33d4n** [yellowblood/btcils#2]
The **Buy** and **Sell** price do not match the data from the exchange:

![image](https://user-images.githubusercontent.com/8020386/103498124-a40b9380-4e7e-11eb-810d-fb8d08c0aac4.png)

**Comment by yellowblood** [comment]
Notice that the exact values appear in your image on the top (in bit2c site). Maybe they cache these values so they're not always up-to-date.

**Comment by l33d4n** [comment]
It worked out a few hours later. Probably a temporary issue.
